/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author andreaorjuela
 */
public class PaginaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PaginaPrincipal
     */
    public PaginaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        L_text1 = new javax.swing.JLabel();
        L_text2 = new javax.swing.JLabel();
        TF_numero1 = new javax.swing.JTextField();
        TF_numero2 = new javax.swing.JTextField();
        B_operacion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TF_Resultado = new javax.swing.JTextField();
        B_suma = new javax.swing.JButton();
        B_resta = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        L_text1.setFont(new java.awt.Font("Apple Chancery", 1, 18)); // NOI18N
        L_text1.setForeground(new java.awt.Color(255, 153, 153));
        L_text1.setText("Numero 1");

        L_text2.setFont(new java.awt.Font("Apple Chancery", 1, 18)); // NOI18N
        L_text2.setText("Numero 2");

        TF_numero1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        TF_numero1.setForeground(new java.awt.Color(51, 51, 51));
        TF_numero1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        TF_numero2.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        TF_numero2.setForeground(new java.awt.Color(51, 51, 51));
        TF_numero2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        B_operacion.setBackground(new java.awt.Color(255, 153, 153));
        B_operacion.setFont(new java.awt.Font("Luminari", 1, 18)); // NOI18N
        B_operacion.setForeground(new java.awt.Color(255, 153, 153));
        B_operacion.setText("x");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Bradley Hand", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Resultado");

        TF_Resultado.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        TF_Resultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        B_suma.setBackground(new java.awt.Color(204, 255, 255));
        B_suma.setFont(new java.awt.Font("Luminari", 1, 18)); // NOI18N
        B_suma.setForeground(new java.awt.Color(0, 204, 204));
        B_suma.setText("+");

        B_resta.setFont(new java.awt.Font("Luminari", 1, 18)); // NOI18N
        B_resta.setForeground(new java.awt.Color(102, 0, 102));
        B_resta.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(L_text1)
                                    .addComponent(L_text2))
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(54, 54, 54)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TF_Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TF_numero1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                .addComponent(TF_numero2))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B_suma)
                        .addGap(18, 18, 18)
                        .addComponent(B_resta)
                        .addGap(18, 18, 18)
                        .addComponent(B_operacion)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_text1)
                    .addComponent(TF_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_text2)
                    .addComponent(TF_numero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_operacion)
                    .addComponent(B_suma)
                    .addComponent(B_resta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TF_Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton B_operacion;
    public javax.swing.JButton B_resta;
    public javax.swing.JButton B_suma;
    private javax.swing.JLabel L_text1;
    private javax.swing.JLabel L_text2;
    public javax.swing.JTextField TF_Resultado;
    public javax.swing.JTextField TF_numero1;
    public javax.swing.JTextField TF_numero2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
